# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run on Chrom 83

    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.0-chrome83-ff77

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm ci
        $(npm bin)/cypress verify
    - run: npm run build --if-present
    - name: Run Cypress tests
      run: |
        # npm run start:ci &
          # run Cypress tests in Chrome
        npx cypress run --browser chrome
      continue-on-error: false
    - name: Copy test execution video and screenshots 
      run:  |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots
    - name: Merge Test Report
      run: npm run combind:report
    - name: Generate HTML Report
      run: npm run generate:report

    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        public_dir: ./public
    
